name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          yarn
          yarn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          yarn
          yarn pretest
          yarn test
      
        
