name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          yarn
          yarn compile
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - run: |
#           yarn
#           yarn pretest
#           yarn test
      
        
